dist: xenial
language: python
cache: pip

env:
  global:
    TOXENV: python

matrix:
  fast_finish: true
  allow_failures:
    - env:
        TOXENV: lint-mypy

  include:
    - python: 3.7
      name: Linting code smells and metadata
      env:
        TOXENV: lint
    - python: 3.7
      name: Linting type matching
      env:
        TOXENV: lint-mypy
    - python: 3.7
      name: Making sure that docs build is healthy
      env:
        TOXENV: docs
    - python: 3.7
    - python: 2.7
    - python: pypy3.5-6.0
    - python: 3.6
    - python: 3.5
    - python: 3.4
    - python: pypy2.7-6.0

install:
  - pip install tox codecov

script:
  - tox

after_success:
  - codecov --env TRAVIS_OS_NAME,TOXENV

notifications:
  irc:
    channels:
      - "irc.freenode.org#pypa-dev"
    use_notice: true
    skip_join: true
