language: python

matrix:
  include:
    - python: 2.7
      env: TOXENV=py27
    - python: 3.6
      env: TOXENV=lint
    - python: 3.4
      env: TOXENV=py34
    - python: 3.5
      env: TOXENV=py35
    - python: 3.6
      env: TOXENV=py36
    - python: 3.6
      env: TOXENV=docs
    - python: 3.6
      env: TOXENV=pypy

install:
  # Add the PyPy repository
  - "if [[ $TOXENV == 'pypy' ]]; then sudo add-apt-repository -y ppa:pypy/ppa; fi"
  - "if [[ $TOXENV == 'pypy' ]]; then sudo sudo apt-get -y update; fi"
  # Upgrade PyPy
  - "if [[ $TOXENV == 'pypy' ]]; then sudo apt-get -y install pypy; fi"
  # This is required because we need to get rid of the Travis installed PyPy
  # or it'll take precedence over the PPA installed one.
  - "if [[ $TOXENV == 'pypy' ]]; then sudo rm -rf /usr/local/pypy/bin; fi"
  - pip install tox codecov

script:
  - tox

after_success:
  - codecov --env TRAVIS_OS_NAME,TOXENV

notifications:
  irc:
    channels:
      - "irc.freenode.org#pypa-dev"
    use_notice: true
    skip_join: true
